FROM node:20-alpine

RUN apk add --no-cache git python3 make g++

WORKDIR /evolution

RUN git clone --depth=1 --branch 2.3.7 https://github.com/EvolutionAPI/evolution-api.git .

RUN npm install

RUN npx prisma generate --schema ./prisma/postgresql-schema.prisma

RUN npm run build

EXPOSE 8080

CMD ["/bin/sh", "-c", ". ./Docker/scripts/deploy_database.sh && npm run start:prod"]
